/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odp;
import java.sql.*;
import javax.swing.*;

import java.sql.Connection;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Personal
 */
public class Newapplication extends javax.swing.JFrame {

    /**
     * Creates new form Newapplication
     */
    public String optionid;
    
    public String Content[]= new String [1000];
    public String Title[]= new String [1000];
    public String Content2[]= new String [1000];
    public String Title2[]= new String [1000];
        
    private Object editorPaneField;

    
    public Newapplication() {
        initComponents();
         
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        templist2 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        tempBsave = new javax.swing.JButton();
        exitbutton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        editorField = new javax.swing.JEditorPane();
        titleField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        templist1 = new javax.swing.JList();
        refresh2 = new javax.swing.JButton();
        refresh1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        docBsave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Application");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        templist2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        templist2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                templist2ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(templist2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Templates");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tempBsave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tempBsave.setText("Save as Template");
        tempBsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempBsaveActionPerformed(evt);
            }
        });

        exitbutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exitbutton.setText("Exit");
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(editorField);

        titleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("User templates");
        jLabel3.setToolTipText("");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        templist1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        templist1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                templist1ValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(templist1);

        refresh2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        refresh2.setText("Refresh");
        refresh2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        refresh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh2ActionPerformed(evt);
            }
        });

        refresh1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        refresh1.setText("Refresh");
        refresh1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        refresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        docBsave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        docBsave.setText("Save as Document");
        docBsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docBsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titleField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(tempBsave)
                                .addGap(36, 36, 36)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(docBsave))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addGap(47, 47, 47)))
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(refresh2)
                                        .addGap(103, 103, 103))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(refresh1)
                                        .addGap(113, 113, 113))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(97, 97, 97))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(refresh1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(refresh2)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempBsave)
                    .addComponent(jButton1)
                    .addComponent(exitbutton)
                    .addComponent(docBsave))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tempBsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempBsaveActionPerformed
        // TODO add your handling code here:
        String author = optionid;
        String title = titleField.getText();
        String content = editorField.getText();
        
        try{
            Connection con =Myconnect.ConnectedDB();
            Statement stmt = con.createStatement();
            
            String query = "INSERT INTO  tempapplications(Author, Title, Content)" + "VALUES ('" +author+ "','" +title+ "','" +content+"')";
            
            System.out.println(query);
            
            int value = stmt.executeUpdate(query);
            if(value > 0){
                JOptionPane.showMessageDialog(null,"Saved!");
               
                
                      
            }else{
                JOptionPane.showMessageDialog(null,"Save Failed!");
            }
              con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
            
                    
        
        
       
    }//GEN-LAST:event_tempBsaveActionPerformed

    private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed
        // TODO add your handling code here:
        Options a= new Options();
        a.setVisible(true);
                           
        this.setVisible(false);
    }//GEN-LAST:event_exitbuttonActionPerformed

    private void refresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh1ActionPerformed
        // TODO add your handling code here:
        DefaultListModel lst = new  DefaultListModel();
        
     try{
         Connection con = Myconnect.ConnectedDB();
        Statement stmt = con.createStatement();
        
        String query ="SELECT *FROM `tempapplications` WHERE `Author` = -1";
        ResultSet result =stmt.executeQuery(query);
        int i=0;
         while(result.next())
                    {
                    String title = result.getString("Title");
                    Content2[i]= result.getString("Content");
                    Title2[i] = title;
                    i++;
                    lst.addElement (title);
                    }
         templist1.setModel(lst);
     }
     catch(Exception e){
            
            JOptionPane.showMessageDialog(null,"Error while connecting!");
        }
        
    }//GEN-LAST:event_refresh1ActionPerformed

    private void refresh2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh2ActionPerformed
        // TODO add your handling code here:
        DefaultListModel lst = new  DefaultListModel();
     try{
         Connection con = Myconnect.ConnectedDB();
        Statement stmt = con.createStatement();
        
        String query ="SELECT *FROM `tempapplications` WHERE `Author` != -1";
        ResultSet result =stmt.executeQuery(query);
        int i=0;
         while(result.next())
                    {
                    String title = result.getString("Title");
                    Content[i]= result.getString("Content");
                    Title[i] = title;
                    i++;
                    lst.addElement (title);
                    }
         templist2.setModel(lst);
     }
     catch(Exception e){
            
            JOptionPane.showMessageDialog(null,"Error while connecting!");
        }
        
    }//GEN-LAST:event_refresh2ActionPerformed

    
    
    
    private void templist2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_templist2ValueChanged
        // TODO add your handling code here:
        int id = templist2.getSelectedIndex();
    editorField.setText(Content[id]);
        titleField.setText(Title[id]);
        
        
    }//GEN-LAST:event_templist2ValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        editorField.setText(" ");
        titleField.setText(" ");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void titleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleFieldActionPerformed

    private void templist1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_templist1ValueChanged
        // TODO add your handling code here:
        
        int id = templist1.getSelectedIndex();
    editorField.setText(Content2[id]);
        titleField.setText(Title2[id]);
    }//GEN-LAST:event_templist1ValueChanged

    private void docBsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docBsaveActionPerformed
        // TODO add your handling code here:
        
        String author = optionid;
        String title = titleField.getText();
        String content = editorField.getText();
        
        try{
            Connection con =Myconnect.ConnectedDB();
            Statement stmt = con.createStatement();
            
            String query = "INSERT INTO  newtemplates(Author, Title, Content)" + "VALUES ('" +author+ "','" +title+ "','" +content+"')";
            String query2 = "INSERT INTO  tempapplications(Author, Title, Content)" + "VALUES ('" +author+ "','" +title+ "','" +content+"')";
            System.out.println(query);
            
            int value = stmt.executeUpdate(query);
              int value2 = stmt.executeUpdate(query2);
            if(value > 0  && value2>0){
                JOptionPane.showMessageDialog(null,"Saved!");
                
                      
            }else{
                JOptionPane.showMessageDialog(null,"Save Failed!");
            }
              con.close();
              System.out.println(content);
              SaveAsDocs newDoc =new SaveAsDocs(title,content);
              newDoc.save();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
        
        
        
    }//GEN-LAST:event_docBsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Newapplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Newapplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Newapplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Newapplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Newapplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton docBsave;
    private javax.swing.JEditorPane editorField;
    private javax.swing.JButton exitbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton refresh1;
    private javax.swing.JButton refresh2;
    private javax.swing.JButton tempBsave;
    private javax.swing.JList templist1;
    private javax.swing.JList templist2;
    private javax.swing.JTextField titleField;
    // End of variables declaration//GEN-END:variables
}
